### ISSUE TITLE
broken links to notebooks on master page

### ISSUE THREAD

**Issue by rrtucci** [tritemio/nbrun#3] opened 2017-02-23 17:34 UTC
If you look at the following simple example, 
https://github.com/artiste-qb-net/quantum-fog/tree/master/jupyter-notebooks/nbrun-example
the links to the notebooks that are generated by running the master notebook are broken (the links don't normally work on github. You have to run the notebooks on your computer to see what I mean).
P.S. Thanks a lot for your very useful module.

**Comment by tritemio** [comment] 2017-02-26 17:46
Thanks for the report!

I found that links work only under certain circumstances due to limitation of the notebook being a browser app.

In particular, links work if:

1. path arguments for template notebook and output folder are:
    
    - in a subfolder of where `jupyter notebook` was started,
    - **relative** paths, starting from the master-notebook folder.

2. the current working directory in python is where the master notebook is.

Point 1 is needed because the ipython kernel can access the whole file system, while the notebook app can only see folders inside its startup folder. The notebook will consider its startup folder the "root" (thus the need to use relative paths). 

For point 2,  seems like `IPython.display.FileLink()` creates a link relative to the current folder the calling notebook is in. So the link works only if the current working python path (`pwd`) is the folder containing the master notebook. I need to investigate if this is the expected behaviour or a bug in ipython.

**Comment by rrtucci** [comment] 2017-02-27 13:33
Can you assemble the link yourself instead of using FileLink?
You can use getcwd() to get python cwd and ask for paths of master and template notebook relative to python cwd. I have noticed like you said that regardless of python cwd, the html part of a notebook thinks of itself as being inside the ./ directory

**Comment by tritemio** [comment] 2017-02-27 16:59
I suspect that the issue is related to relative links in html&browser. A relative link seem to be relative to the page url. Even assembling the link by yourself, a relative url is resolved by the browser starting from the "folder" of the current page.

Afterall, the FileLink implementation is very simple:
https://github.com/ipython/ipython/blob/d1a99b1639f32fd45496baf5ebc2a557f8a665ed/IPython/lib/display.py#L299

I'll ask the ipython folks if they have any advice. But if you think about it, having relative links that are relative to the current page makes sense. Does not matter where `nbrun` is installed but the relative position of master, template and output notebooks need to be fixed (and within the jupyter notebook startup folder).

**Comment by tritemio** [comment] 2017-02-27 17:42
I found an old issue on ipython that confirms my explanation:

https://github.com/ipython/ipython/issues/8053

**Comment by rrtucci** [comment] 2017-02-27 19:00
Gazie for thinking about it Antonino!
In the example that i linked to in my first post, if I add to
the master notebook a MARKDOWN cell as follows

`<a href="./example-template-notebook-out_0_a.ipynb">link to out_0_a</a>`

It gives a link that works. Alternatively, a MARKDOWN cell 

`[link to out_0_a](./example-template-notebook-out_0_a.ipynb)`

works too. This assumes that master and templates are in same directory. This is slightly different from generating a link as output, but close no?

**Comment by tritemio** [comment] 2017-02-27 20:35
Markdown or output cell should be the same. The nbrun links do not work in your example only because your python cwd is not the same as the master notebook folder. Change back your python dir to the master notebook folder and the issue is fixed.

I don't think that allowing arbitrary cwd in python can be easily fixed in nbrun. The kernel is not supposed to know about the frontend (i.e. if it is run through a notebook or a terminal) and so you can get the notebook path only through very hackish solutions.

It is much easier to just document that the user should not change the current python dir in the notebook otherwise the generated links will be broken.

**Comment by rrtucci** [comment] 2017-02-28 02:47
Va Bene. However, one last comment. I can generate links myself as follows. So maybe you can add an option show_links=True which I could set to False if I wanted

```
from IPython.display import display, FileLink, HTML
def show_link(target, text):
    display(HTML('<a href=' + target + ' target="_blank">' + text + '</a>'))
    
fname = 'example-template-notebook-out_0_a.ipynb'
text = 'look here'
show_link(fname, text)
```

**Comment by rrtucci** [comment] 2017-02-28 03:02
Va Bene. I just realized that I can do an os.chdir() in order to import nbrun.py 
BUT
 I must also do a second os.chdir() immediately after importing nbrun.py
 to go back to the directory of the master before calling run_notebook()

I fixed my example accordingly and all the links now work. I am a satisfied customer

**Closed as completed** 2017-03-07 14:12 UTC
